print("Let's get to know you!")

myName = input("What is your name?: ")
favouriteFood = input("What is your favourite food?: ")
favouriteMusic = input("What is your favourite music?: ")
favouriteActivity = input("What is your favourite activity?: ")
myPlace = input("Where do you live?: ")
print()
print("You are")
print(myName)
print("You are probably hungry for")
print(favouriteFood)
print("and you definitely find yourself bopping along to some")
print(favouriteMusic)
print("while living in the amazing")
print(myPlace)
print()
print("Not only that - you're also great at")
print(favouriteActivity + "!")
